// Motorcycle & Motor Museums — UK, Isle of Man & Ireland
// Curated directory of motorcycle museums and transport/motor museums with
// significant motorcycle collections. Powers the /museums hub + detail pages
// and the "Museums" layer in the interactive Route Builder map.
// Admission/opening verified from official sources (see sourceUrls); always
// confirm on the museum's own site before travelling as prices/hours change.

window.MOTORCYCLE_MUSEUMS = [
  {
    slug: 'national-motorcycle-museum',
    name: 'National Motorcycle Museum',
    region: 'West Midlands',
    country: 'England',
    lat: 52.4447, lng: -1.7064,
    address: 'Coventry Road, Bickenhill, Solihull B92 0EJ',
    summary: 'The world\'s largest collection of British motorcycles, with over 1,000 machines across five halls. An essential stop for British bike fans, just off the M42 (J6) by the NEC.',
    offers: ['1,000+ British motorcycles', 'Five exhibition halls', 'Cafe and food court', 'Gift shop', 'Free parking', 'Cashless site (card only)'],
    highlights: ['World-famous Brough Superior and Vincent machines', 'Restored classics from 1898 to the present day'],
    admission: 'Adults £17, seniors £15, children 5-15 £10, family £45 (2026)',
    opening: 'Daily 08:30-17:30, last admission 16:30 (closed 24-26 Dec & 1 Jan)',
    duration: '2-3 hours',
    phone: '+44 1675 443311',
    website: 'https://www.nationalmotorcyclemuseum.co.uk/',
    founded: 1984,
    notes: 'Cashless site (card only).',
    sourceUrls: ['https://www.nationalmotorcyclemuseum.co.uk/visit-us/opening-hours-prices/']
  },
  {
    slug: 'sammy-miller-motorcycle-museum',
    name: 'Sammy Miller Motorcycle Museum',
    region: 'Hampshire',
    country: 'England',
    lat: 50.7670, lng: -1.6713,
    address: 'Bashley Cross Roads, New Milton, Hampshire BH25 5SZ',
    summary: 'Award-winning museum of 400+ rare and racing motorcycles, most kept in running order, founded by trials legend Sammy Miller on the edge of the New Forest.',
    offers: ['400+ mostly running motorcycles', 'Rare racing and prototype bikes', 'Tearooms', 'Craft and gift shops', 'Animal paddock', 'Free parking (coaches welcome)'],
    highlights: ['One-off and championship-winning competition machines', 'Living-museum ethos with on-site restoration workshop'],
    admission: 'Adults £16, seniors (66+) £14, juniors 7-16 £8, family £40, under 6 free (2026)',
    opening: 'Daily 10:00-16:30, last admission 14:30; reduced winter hours from early Nov',
    duration: '2-3 hours',
    phone: '+44 1425 620777',
    website: 'https://sammymiller.co.uk/',
    founded: 1983,
    notes: 'Collection began 1964; public museum opened 1983. In Jan to mid-Feb often open Fri-Sun only, so check before travelling.',
    sourceUrls: ['https://sammymiller.co.uk/book-tickets/', 'https://sammymiller.co.uk/opening-times/']
  },
  {
    slug: 'coventry-transport-museum',
    name: 'Coventry Transport Museum',
    region: 'West Midlands',
    country: 'England',
    lat: 52.4108, lng: -1.5102,
    address: 'Millennium Place, Hales Street, Coventry CV1 1JD',
    summary: 'The largest publicly owned collection of British road transport, including Coventry-built motorcycles and the land speed record cars Thrust2 and ThrustSSC, in the heart of Coventry.',
    offers: ['250+ cars and commercial vehicles', 'Coventry-built motorcycle displays', 'Thrust2 & ThrustSSC record cars', '4D simulator', 'Cafe and shop', '12-month re-entry ticket'],
    highlights: ['World land speed record cars Thrust2 and ThrustSSC', 'Local marques incl. Triumph, Rudge and Coventry Eagle'],
    admission: 'Adults £15.50 (£17 on the day), concessions £12, juniors 5-16 £8.50, family of 4 £38.50; ticket valid 12 months (2026)',
    opening: 'Tue-Sun & Bank Holiday Mondays 10:00-17:00, last admission 16:30 (closed 24-26 Dec & 1 Jan)',
    duration: '2-3 hours',
    phone: '+44 24 7623 4270',
    website: 'https://www.transport-museum.com/',
    founded: 1980,
    notes: 'Entry is now a paid 12-month ticket (no longer free).',
    sourceUrls: ['https://www.transport-museum.com/admission-prices.aspx', 'https://www.transport-museum.com/visiting/opening-hours-prices.aspx']
  },
  {
    slug: 'national-motor-museum-beaulieu',
    name: 'National Motor Museum, Beaulieu',
    region: 'Hampshire',
    country: 'England',
    lat: 50.8204, lng: -1.4521,
    address: 'Beaulieu, Brockenhurst, Hampshire SO42 7ZN',
    summary: 'One of the UK\'s great motoring collections (280+ vehicles) set within the wider Beaulieu attraction. A strong full day out for touring riders in the New Forest.',
    offers: ['280+ vehicles incl. motorcycles', 'Palace House & Gardens', 'Beaulieu Abbey', 'World of Top Gear exhibition', 'Monorail and rides', 'Restaurant and shop'],
    highlights: ['Land speed record cars including Bluebird', 'Motorsport and motorcycle galleries'],
    admission: 'Inclusive ticket: adult £31.50 (£28.35 advance), child 4-16 £18.50, under 3 free, family from £70 (2026)',
    opening: 'Daily from 10:00 (to 17:00; to 18:00 late May to mid-Sep), closed Christmas Day',
    duration: 'Half to full day',
    phone: '+44 1590 612345',
    website: 'https://www.beaulieu.co.uk/',
    founded: 1952,
    notes: 'One ticket covers all Beaulieu attractions; Gift Aid upgrades it to an annual pass. Opened as the Montagu Motor Museum in 1952; renamed National Motor Museum in 1972.',
    sourceUrls: ['https://www.beaulieu.co.uk/plan-your-visit/ticket-prices/', 'https://www.beaulieu.co.uk/plan-your-visit/opening-times/']
  },
  {
    slug: 'haynes-international-motor-museum',
    name: 'Haynes International Motor Museum',
    region: 'Somerset',
    country: 'England',
    lat: 51.0456, lng: -2.5493,
    address: 'Sparkford, Yeovil, Somerset BA22 7LH',
    summary: 'The UK\'s largest collection of cars and motorbikes from around the world (400+ vehicles), with a dedicated motorcycle hall, handily placed near the A303 in Somerset.',
    offers: ['400+ cars and motorcycles', 'Dedicated motorcycle displays', 'Cafe 750', 'Gift shop', 'Outdoor play area and karts', 'Free parking', '12-month pass included'],
    highlights: ['The Red Room of red sports cars', 'International motorcycle gallery'],
    admission: 'Adults £24.95, concessions £21, children 4-15 £14.20; under 4 free; save 10% online; annual pass included (2026)',
    opening: 'Daily 10:00-17:30, last entry 16:30 (reduced hours in winter, check calendar)',
    duration: '2-3 hours',
    phone: '+44 1963 440804',
    website: 'https://www.haynesmuseum.org/',
    founded: 1985,
    notes: 'Standard tickets auto-upgrade to a 12-month annual pass via Gift Aid. Hours vary seasonally.',
    sourceUrls: ['https://www.haynesmuseum.org/plan-your-visit/faqs/', 'https://www.haynesmuseum.org/plan-your-visit/opening-times/']
  },
  {
    slug: 'lakeland-motor-museum',
    name: 'Lakeland Motor Museum',
    region: 'Cumbria',
    country: 'England',
    lat: 54.2607, lng: -2.9890,
    address: 'Old Blue Mill, Backbarrow, Ulverston, Cumbria LA12 8TA',
    summary: 'A 30,000-exhibit collection of classic cars, motorcycles, scooters and bicycles beside the River Leven in the southern Lake District, including a Campbell Bluebird tribute.',
    offers: ['140+ classic cars and motorcycles', '30,000 motoring exhibits', 'Campbell Bluebird Exhibition', 'Riverside Cafe Ambio', 'Gift shop', 'Free parking', 'Dog friendly'],
    highlights: ['Campbell-Bluebird land and water speed record tribute', 'Classic British motorcycles and scooters'],
    admission: 'Adults £13.25, children 5-15 £7.90, family (2+3) £36, under 5 free (valid to 1 Nov 2026)',
    opening: 'Open daily from 09:30 (approx to 17:30); reduced winter hours, confirm last admission online',
    duration: '1.5-2.5 hours',
    phone: '+44 15395 30400',
    website: 'https://www.lakelandmotormuseum.co.uk/',
    founded: 2010,
    notes: 'Relocated to Backbarrow in 2010 (collection originally shown at Holker Hall from 1978). Confirm seasonal hours before visiting.',
    sourceUrls: ['https://www.lakelandmotormuseum.co.uk/visiting/pricing', 'https://whichmuseum.com/museum/lakeland-motor-museum-backbarrow-2840/opening-hours']
  },
  {
    slug: 'brooklands-museum',
    name: 'Brooklands Museum',
    region: 'Surrey',
    country: 'England',
    lat: 51.3531, lng: -0.4707,
    address: 'Brooklands Road, Weybridge, Surrey KT13 0SL',
    summary: 'Birthplace of British motorsport and aviation, on the world\'s first purpose-built race circuit. Banked track, racing cars and motorcycles, plus Concorde and a bus museum.',
    offers: ['Historic racing cars and motorcycles', 'Original banked Brooklands circuit', 'Concorde and aviation halls', 'London Bus Museum on site', 'Cafe and shop', 'Driving experiences (extra cost)'],
    highlights: ['The famous Brooklands banking and Test Hill', 'Motorcycle racing heritage and record-breakers'],
    admission: 'Summer: adult £25.70 advance (£27.10 on the day), child 4-17 £10.70, under 4 free; lower winter rates (2026)',
    opening: 'Daily, summer 10:00-17:00 (to 1 Nov), winter 10:00-16:00 (from 2 Nov); last entry 2 hours before closing',
    duration: '3-4 hours',
    phone: '+44 1932 857381',
    website: 'https://www.brooklandsmuseum.com/',
    founded: 1991,
    notes: 'Cashless since 1 Jan 2026. A motorsport/aviation museum with motorcycles rather than a dedicated bike museum.',
    sourceUrls: ['https://www.brooklandsmuseum.com/visit/tickets-prices/', 'https://www.brooklandsmuseum.com/visit/opening-times/']
  },
  {
    slug: 'atwell-wilson-motor-museum',
    name: 'Atwell-Wilson Motor Museum',
    region: 'Wiltshire',
    country: 'England',
    lat: 51.4242, lng: -1.9948,
    address: 'Stockley Lane, Calne, Wiltshire SN11 0NF',
    summary: 'A small, friendly volunteer-run Wiltshire museum with 100+ cars plus motorcycles, mopeds and bicycles, a 1930s-style garage and a growing motorsport display.',
    offers: ['100+ cars, motorcycles and bicycles', 'Reconstructed 1930s-style garage', 'Williams F1 cars on display', 'Refreshments and seating area', 'Free parking', 'Dog friendly'],
    highlights: ['Eclectic motorcycle, moped and bicycle collection', 'Jack French / 750 Formula motorsport exhibits'],
    admission: 'Adults £12, children 5-16 £5, family (2+3) £30, under 5 free (2026)',
    opening: 'Tue-Sun & Bank Holiday Mondays 10:00-16:00, last admission 15:00; open 1 Feb-30 Nov (closed Dec-Jan)',
    duration: '1-2 hours',
    phone: '+44 1249 813119',
    website: 'https://atwellwilson.org.uk/',
    founded: 1989,
    notes: 'Run as a charity since 1997.',
    sourceUrls: ['https://atwellwilson.org.uk/', 'https://atwellwilson.org.uk/about-the-museum/']
  },
  {
    slug: 'grampian-transport-museum',
    name: 'Grampian Transport Museum',
    region: 'Aberdeenshire',
    country: 'Scotland',
    lat: 57.2332, lng: -2.7016,
    address: 'Montgarrie Road, Alford AB33 8AE',
    summary: 'Award-winning independent transport museum with cars, motorcycles and commercial vehicles, hands-on exhibits and an outdoor road circuit; strong North-East Scotland motoring heritage.',
    offers: ['Cars, motorcycles & commercial vehicles', 'Hands-on interactive exhibits', 'Outdoor road circuit', 'Motorbites tearoom', 'Gift shop', 'Free parking', 'Dog-friendly'],
    highlights: ['Craigievar Express steam tricycle (1895)', 'Historic motorcycles', '1914 Sentinel steam waggon', 'Ex-Top Gear vehicles'],
    admission: 'Adults £14, concession (60+) £12, child (3-15) £5, family from £27 (2026)',
    opening: 'Seasonal: daily 10:00-17:00, 28 Mar-26 Oct (closes 16:00 in Oct); closed Nov-late Mar',
    duration: '2-3 hours',
    phone: '+44 1975 562292',
    website: 'https://www.gtm.org.uk/',
    founded: 1983,
    notes: 'Seasonal opening, closed in winter.',
    sourceUrls: ['https://www.gtm.org.uk/visit/opening-times-and-prices/']
  },
  {
    slug: 'riverside-museum',
    name: 'Riverside Museum',
    region: 'Glasgow',
    country: 'Scotland',
    lat: 55.8656, lng: -4.3064,
    address: '100 Pointhouse Place, Glasgow G3 8RS',
    summary: 'Glasgow\'s award-winning transport and technology museum in a Zaha Hadid building, holding one of the world\'s finest transport collections including a wall of motorcycles and Scottish-built bikes. Free entry.',
    offers: ['Cars, motorcycles, trams & locomotives', 'Recreated historic Glasgow street', 'Interactive displays', 'Riverside Cafe', 'Gift shop', 'Tall Ship Glenlee alongside (free)'],
    highlights: ['Motorcycle display wall', 'Scottish-built motorcycles & cars', 'Recreated cobbled street scene'],
    admission: 'Free entry (donations welcome) (2026)',
    opening: 'Year-round: Mon-Thu & Sat 10:00-17:00, Fri & Sun 11:00-17:00',
    duration: '2-3 hours',
    phone: '+44 141 287 2720',
    website: 'https://www.glasgowlife.org.uk/museums/venues/riverside-museum',
    founded: 2011,
    notes: 'Free admission. Public transport recommended (limited parking).',
    sourceUrls: ['https://www.glasgowlife.org.uk/museums/venues/riverside-museum']
  },
  {
    slug: 'myreton-motor-museum',
    name: 'Myreton Motor Museum',
    region: 'East Lothian',
    country: 'Scotland',
    lat: 56.0080, lng: -2.8309,
    address: 'Aberlady, East Lothian EH32 0PZ',
    summary: 'Traditional family museum (founded 1966) with a characterful collection of cars, motorcycles, bicycles and commercial vehicles from 1899 onward, plus period advertising and memorabilia.',
    offers: ['Cars, motorcycles & cycles', 'Commercial vehicles', 'Period advertising & enamel signs', 'Toy vehicles', 'Free parking'],
    highlights: ['Vintage British motorcycles', 'Vehicles dating from 1899', 'Period motoring memorabilia'],
    admission: 'Adults £10, concession £8, child £5 - cash only (2026)',
    opening: 'Mar-Oct daily 10:30-16:30; Nov-Feb Wed-Sun 10:30-15:00',
    duration: '1-2 hours',
    phone: '+44 7585 356931',
    website: 'https://www.myretonmotormuseum.co.uk/',
    founded: 1966,
    notes: 'Cash only - no card payments. Confirm winter hours before a visit.',
    sourceUrls: ['https://www.myretonmotormuseum.co.uk/coll-page-section/admission/']
  },
  {
    slug: 'llangollen-motor-museum',
    name: 'Llangollen Motor Museum',
    region: 'Denbighshire',
    country: 'Wales',
    lat: 52.9839, lng: -3.1836,
    address: 'Pentrefelin, Llangollen LL20 8EE',
    summary: 'Small, characterful family-run museum (est. 1986) with 60+ cars and motorcycles plus motoring memorabilia and a classic spares / autojumble service.',
    offers: ['60+ classic cars & motorcycles', 'Motoring memorabilia & ephemera', 'Classic spares / autojumble', 'Free on-site parking'],
    highlights: ['Vintage & classic motorcycles', 'Cars from 1916 onward', 'Quirky motoring nostalgia displays'],
    admission: 'Modest entry fee charged; current price not published online - confirm with museum (2026)',
    opening: 'Open 1st-7th of each month plus weekends; groups by arrangement (phone ahead)',
    duration: '1-2 hours',
    phone: '+44 7780 306220',
    website: 'https://www.llangollenmotormuseum.co.uk/',
    founded: 1986,
    notes: 'Unusual limited opening pattern (1st-7th of month + weekends) - phone ahead. Admission price not verifiable online.',
    sourceUrls: ['https://www.llangollenmotormuseum.co.uk/', 'https://en.wikipedia.org/wiki/Llangollen_Motor_Museum']
  },
  {
    slug: 'tacla-taid-anglesey-transport-museum',
    name: 'Tacla Taid - The Anglesey Transport Museum',
    region: 'Anglesey',
    country: 'Wales',
    lat: 53.1738, lng: -4.3485,
    address: 'Tyddyn Pwrpas, Newborough, Anglesey LL61 6TN',
    summary: 'The largest transport museum in Wales (120+ vehicles) set in a replica 1940s cobbled street, with classic cars, motorbikes, tractors, military vehicles and a cafe.',
    offers: ['120+ classic vehicles', 'Motorbikes, cars & tractors', 'Replica 1940s cobbled street', 'Military vehicles & a jet plane', 'On-site cafe', 'Kids play area', 'On-site accommodation'],
    highlights: ['Classic British motorcycles', 'Vehicles seen on TV & film', '1940s street scene', 'Land Rover collection'],
    admission: 'Adults (16+) £12, child (6-15) £6, under 6 free, family £35 (2026)',
    opening: 'Open daily 10:00-16:00 (confirm seasonal hours in winter)',
    duration: '1.5-2.5 hours',
    phone: '+44 1248 440344',
    website: 'https://angleseytransportmuseum.co.uk/',
    founded: null,
    notes: 'Official site lists daily 10:00-16:00; some sources state Easter-end Oct seasonal opening - confirm before a winter visit.',
    sourceUrls: ['https://angleseytransportmuseum.co.uk/']
  },
  {
    slug: 'isle-of-man-motor-museum',
    name: 'Isle of Man Motor Museum',
    region: 'Jurby',
    country: 'Isle of Man',
    lat: 54.3602, lng: -4.5233,
    address: 'Jurby Industrial Estate, Jurby IM7 3BD',
    summary: 'Huge privately-funded museum on former RAF Jurby with 500+ vehicles, including a major collection of rarely-seen private motorcycles and TT heritage - a must for TT and bike fans.',
    offers: ['500+ cars & motorcycles', 'Rare private motorcycle collection', 'TT & motorsport heritage', 'Workshop tours', 'Old Guardhouse Coffeehouse cafe', 'Free parking', 'Lifts to motorcycle mezzanines'],
    highlights: ['Extensive motorcycle galleries', 'TT racing machines & history', 'Rare and exotic vehicles'],
    admission: 'Adults £22, concession £20, child (5-15) £11, under 5 free, family £55 (2026)',
    opening: 'Summer 28 Mar-5 Oct daily 10:00-17:00; from 9 Oct Thu-Sun; Nov Sundays only',
    duration: '3-4 hours',
    phone: '+44 1624 888333',
    website: 'https://www.isleofmanmotormuseum.com/',
    founded: 2015,
    notes: 'Seasonal, with very limited winter opening. Large site - allow plenty of time.',
    sourceUrls: ['https://www.isleofmanmotormuseum.com/plan-your-visit/']
  },
  {
    slug: 'manx-museum',
    name: 'Manx Museum',
    region: 'Douglas',
    country: 'Isle of Man',
    lat: 54.1527, lng: -4.4806,
    address: 'Kingswood Grove, Douglas IM1 3LY',
    summary: 'The Isle of Man\'s national museum (free entry) covering 10,000 years of history, including a dedicated Isle of Man TT Gallery celebrating the races, legendary riders and their machines.',
    offers: ['Isle of Man TT Gallery', 'Viking & Celtic treasures', 'National Art Gallery', 'Natural History Gallery', 'Gift shop', 'National Library & Archives', 'Wheelchair accessible'],
    highlights: ['TT Gallery: legendary riders & race motorcycles', 'Viking silver hoards', 'Story of the Holiday Isle'],
    admission: 'Free entry (suggested £10 voluntary donation) (2026)',
    opening: 'Open daily 09:30-16:30',
    duration: '1.5-2 hours',
    phone: '+44 1624 648000',
    website: 'https://manxnationalheritage.im/our-sites/manx-museum/',
    founded: 1922,
    notes: 'Free national museum; motorcycle interest is concentrated in the dedicated TT Gallery (opened 2023).',
    sourceUrls: ['https://manxnationalheritage.im/our-sites/manx-museum/']
  },
  {
    slug: 'murrays-motorcycle-museum',
    name: 'Murray\'s Motorcycle Museum',
    region: 'Santon',
    country: 'Isle of Man',
    lat: 54.1181, lng: -4.5869,
    address: 'Santon Villa, Santon IM4 1EN',
    summary: 'The Isle of Man\'s oldest motorcycle museum (established 1964), reopened at Santon, packed with 150+ classic and racing bikes plus TT memorabilia - a genuine pilgrimage for bike enthusiasts.',
    offers: ['150+ classic & racing motorcycles', 'TT & road-racing memorabilia', 'On main Douglas-Castletown road (A5)', 'Open 7 days a week', 'Bus stop & rail station nearby'],
    highlights: ['Historic TT and racing motorcycles', 'Rare classic bikes', 'Motorcycling memorabilia'],
    admission: 'Entry £10 per person (2026)',
    opening: 'Open 7 days a week (warm-season attraction; confirm winter opening by phone)',
    duration: '1-1.5 hours',
    phone: '+44 1624 823223',
    website: 'https://www.murraysmotorcyclemuseum.com/',
    founded: 1964,
    notes: 'Reopened at Santon Villa, Santon (formerly at the Bungalow on the TT Mountain Course).',
    sourceUrls: ['https://www.murraysmotorcyclemuseum.com/', 'https://www.visitisleofman.com/experience/murrays-motorcycle-museum-p1315821']
  },
  {
    slug: 'national-transport-museum-of-ireland',
    name: 'National Transport Museum of Ireland',
    region: 'County Dublin',
    country: 'Ireland',
    lat: 53.3868, lng: -6.0810,
    address: 'Heritage Depot, Howth Demesne, Howth, Co. Dublin',
    summary: 'Volunteer-run museum in the grounds of Howth Castle with 60+ historic vehicles on display - buses, trams, fire engines, commercial and military vehicles dating 1880s-1984.',
    offers: ['Vintage buses, trams & commercials', 'Fire & emergency vehicles', 'Military & utility vehicles', 'Hill of Howth electric tram', 'Free parking'],
    highlights: ['Restored Hill of Howth No.9 tram', 'Vintage Irish buses', 'Fire engines & commercials'],
    admission: 'Small entry fee (cash); current prices not published online - confirm with museum (2026)',
    opening: 'Sat, Sun & bank holidays 14:00-17:00 (also daily 14:00-17:00 the week after Christmas)',
    duration: '1-1.5 hours',
    phone: '+353 1 832 0427',
    website: 'https://www.nationaltransportmuseum.ie/',
    founded: 1949,
    notes: 'Open weekends/bank holidays only. Primarily buses, trams and commercial vehicles - limited motorcycle content.',
    sourceUrls: ['https://www.nationaltransportmuseum.org/info.html', 'https://www.visitdublin.com/national-transport-museum-of-ireland']
  },
  {
    slug: 'ulster-transport-museum',
    name: 'Ulster Transport Museum',
    region: 'County Down',
    country: 'Northern Ireland',
    lat: 54.6540, lng: -5.8018,
    address: 'Bangor Road, Cultra, Holywood BT18 0EU',
    summary: 'One of Europe\'s most comprehensive transport collections, telling the story of transport and innovation in Ulster across road, rail, sea and air, with a road gallery featuring motorcycles.',
    offers: ['Road, rail, sea & air transport', 'Motorcycles & cars', 'Museum of Innovation (DeLorean, Ferguson tractor)', 'Irish Railway Collection', 'Gift shop & cafe', 'Outdoor grounds (free)'],
    highlights: ['Motorcycle & cycle displays', 'The DeLorean DMC-12', 'Irish railway locomotives'],
    admission: 'Adults £12, seniors/students £9.45, child £7.45, family from £24 (2026)',
    opening: 'Summer (1 Mar-30 Sep) Tue-Sun 10:00-17:00; Winter (1 Oct-28 Feb) Tue-Fri 10:00-16:00, Sat-Sun 11:00-16:00',
    duration: '2-3 hours',
    phone: '+44 28 9042 8428',
    website: 'https://www.ulstertransportmuseum.org/',
    founded: 1962,
    notes: 'Operates separately from the adjacent Ulster Folk Museum (separate tickets). Pre-booking recommended.',
    sourceUrls: ['https://www.ulstertransportmuseum.org/booking-arrival', 'https://whichmuseum.com/museum/ulster-transport-museum-holywood-44372/tickets-prices']
  }
];

// Map-maker POI adapter: expose museums in the shape the Route Builder POI layer
// expects ({ name, lat, lng, desc, url, rating, top }) without duplicating data.
window.MOTORCYCLE_MUSEUMS_POI = window.MOTORCYCLE_MUSEUMS.map(function (m) {
  return {
    name: m.name,
    lat: m.lat,
    lng: m.lng,
    desc: m.summary,
    url: '/museums/' + m.slug,
    rating: 5,
    top: true
  };
});
