export type CuratedRoute = {
  id: string;
  name: string;
  description: string;
  waypoints: { lat: number; lng: number; name?: string }[];
  settings: { road_preference: 'curvy' | 'twisty' | 'fast' };
  is_public: true;
  curviness_score: number;
  difficulty: 'easy' | 'moderate' | 'challenging';
  region: 'scotland' | 'wales' | 'england-north' | 'england-midlands' | 'england-south' | 'isle-of-man';
  distance_miles: number;
  tags: string[];
};

export const curatedRoutes: CuratedRoute[] = [
  {
    id: 'cat-and-fiddle-a537',
    name: 'Cat and Fiddle (A537)',
    description: 'One of England\'s most famous biking roads climbing from Macclesfield to Buxton across exposed moorland with sweeping bends and stunning views.',
    waypoints: [
      { lat: 53.2601, lng: -2.1253, name: 'Macclesfield' },
      { lat: 53.2455, lng: -2.0580, name: 'Walker Barn' },
      { lat: 53.2361, lng: -1.9873, name: 'Cat and Fiddle Inn' },
      { lat: 53.2510, lng: -1.9420, name: 'Burbage' },
      { lat: 53.2594, lng: -1.9145, name: 'Buxton' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 8,
    difficulty: 'moderate',
    region: 'england-midlands',
    distance_miles: 12,
    tags: ['twist', 'bend', 'moor', 'scenic', 'peak'],
  },
  {
    id: 'snake-pass-a57',
    name: 'Snake Pass (A57)',
    description: 'Iconic Peak District road with fast sweepers through the Dark Peak. Exposed and dramatic in all weathers with relentless curves.',
    waypoints: [
      { lat: 53.4430, lng: -1.9490, name: 'Glossop' },
      { lat: 53.4250, lng: -1.9080, name: 'Snake Pass Inn' },
      { lat: 53.4180, lng: -1.8640, name: 'Snake Summit' },
      { lat: 53.3950, lng: -1.7830, name: 'Ashopton' },
      { lat: 53.3870, lng: -1.7530, name: 'Ladybower' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 7,
    difficulty: 'moderate',
    region: 'england-north',
    distance_miles: 14,
    tags: ['twist', 'bend', 'snake', 'moor', 'pass', 'scenic'],
  },
  {
    id: 'hardknott-pass',
    name: 'Hardknott Pass',
    description: 'England\'s steepest road with 30% gradients and vicious hairpins. A serious challenge rewarded by breathtaking Lakeland views.',
    waypoints: [
      { lat: 54.3940, lng: -3.2810, name: 'Eskdale' },
      { lat: 54.3980, lng: -3.2450, name: 'Hardknott Roman Fort' },
      { lat: 54.4020, lng: -3.2130, name: 'Hardknott Summit' },
      { lat: 54.4120, lng: -3.1650, name: 'Cockley Beck' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 10,
    difficulty: 'challenging',
    region: 'england-north',
    distance_miles: 5,
    tags: ['hairpin', 'pass', 'switchback', 'fell', 'scenic', 'mountain'],
  },
  {
    id: 'wrynose-pass',
    name: 'Wrynose Pass',
    description: 'Narrow, steep single-track pass connecting Little Langdale to Cockley Beck. Tight hairpins and stunning fell scenery.',
    waypoints: [
      { lat: 54.4120, lng: -3.1650, name: 'Cockley Beck' },
      { lat: 54.4180, lng: -3.1370, name: 'Wrynose Summit' },
      { lat: 54.4210, lng: -3.1070, name: 'Wrynose Bottom' },
      { lat: 54.4260, lng: -3.0690, name: 'Little Langdale' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 9,
    difficulty: 'challenging',
    region: 'england-north',
    distance_miles: 4,
    tags: ['hairpin', 'pass', 'fell', 'switchback', 'mountain'],
  },
  {
    id: 'bealach-na-ba',
    name: 'Bealach na B\u00e0 (Applecross)',
    description: 'Scotland\'s most spectacular mountain pass with alpine-style hairpins rising to 626m. The greatest motorcycle road in Britain.',
    waypoints: [
      { lat: 57.3930, lng: -5.6520, name: 'Kishorn' },
      { lat: 57.4080, lng: -5.7100, name: 'Lower Hairpins' },
      { lat: 57.4170, lng: -5.7460, name: 'Bealach Summit' },
      { lat: 57.4340, lng: -5.8100, name: 'Applecross' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 10,
    difficulty: 'challenging',
    region: 'scotland',
    distance_miles: 11,
    tags: ['hairpin', 'pass', 'switchback', 'mountain', 'highland', 'scenic', 'summit'],
  },
  {
    id: 'a82-glen-coe',
    name: 'A82 through Glen Coe',
    description: 'Dramatic valley road flanked by towering peaks. Fast sweepers through Scotland\'s most iconic and atmospheric glen.',
    waypoints: [
      { lat: 56.4330, lng: -4.7130, name: 'Tyndrum' },
      { lat: 56.5300, lng: -4.8900, name: 'Bridge of Orchy' },
      { lat: 56.5940, lng: -4.9550, name: 'Rannoch Moor' },
      { lat: 56.6580, lng: -5.0250, name: 'Glencoe Summit' },
      { lat: 56.6820, lng: -5.0970, name: 'Glencoe Village' },
      { lat: 56.8170, lng: -5.1120, name: 'Fort William' },
    ],
    settings: { road_preference: 'fast' },
    is_public: true,
    curviness_score: 6,
    difficulty: 'moderate',
    region: 'scotland',
    distance_miles: 35,
    tags: ['glen', 'highland', 'scenic', 'mountain', 'valley', 'moor'],
  },
  {
    id: 'a87-isle-of-skye',
    name: 'A87 to Isle of Skye',
    description: 'Epic Highland road from Invergarry to Skye Bridge passing Five Sisters of Kintail and dramatic lochs.',
    waypoints: [
      { lat: 57.0430, lng: -4.9690, name: 'Invergarry' },
      { lat: 57.1280, lng: -5.1500, name: 'Loch Cluanie' },
      { lat: 57.1850, lng: -5.3350, name: 'Cluanie Inn' },
      { lat: 57.2160, lng: -5.4280, name: 'Shiel Bridge' },
      { lat: 57.2550, lng: -5.5900, name: 'Dornie' },
      { lat: 57.2790, lng: -5.7130, name: 'Kyle of Lochalsh' },
    ],
    settings: { road_preference: 'fast' },
    is_public: true,
    curviness_score: 5,
    difficulty: 'moderate',
    region: 'scotland',
    distance_miles: 40,
    tags: ['loch', 'highland', 'scenic', 'mountain', 'glen'],
  },
  {
    id: 'black-mountain-pass-a4069',
    name: 'Black Mountain Pass (A4069)',
    description: 'Wales\' finest biking road sweeping over the Black Mountain with open moorland, cattle grids, and flowing bends.',
    waypoints: [
      { lat: 51.9490, lng: -3.7800, name: 'Llangadog' },
      { lat: 51.8950, lng: -3.7900, name: 'Twynllanan' },
      { lat: 51.8600, lng: -3.8200, name: 'Black Mountain Summit' },
      { lat: 51.8240, lng: -3.8500, name: 'Glyntawe' },
      { lat: 51.7950, lng: -3.8700, name: 'Brynamman' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 8,
    difficulty: 'moderate',
    region: 'wales',
    distance_miles: 14,
    tags: ['twist', 'bend', 'moor', 'mountain', 'scenic', 'national park'],
  },
  {
    id: 'horseshoe-pass-a542',
    name: 'Horseshoe Pass (A542)',
    description: 'Sweeping North Wales pass climbing from the Dee Valley with fast open bends and panoramic views across the Vale of Clwyd.',
    waypoints: [
      { lat: 52.9700, lng: -3.1750, name: 'Llangollen' },
      { lat: 52.9950, lng: -3.1800, name: 'Britannia Inn' },
      { lat: 53.0380, lng: -3.1900, name: 'Horseshoe Summit' },
      { lat: 53.0680, lng: -3.2300, name: 'Llandegla' },
    ],
    settings: { road_preference: 'curvy' },
    is_public: true,
    curviness_score: 6,
    difficulty: 'easy',
    region: 'wales',
    distance_miles: 9,
    tags: ['pass', 'scenic', 'valley', 'bend', 'view'],
  },
  {
    id: 'devils-staircase-a4061',
    name: 'Devil\'s Staircase (A4061)',
    description: 'Relentless switchbacks climbing out of the Rhondda Valley over the mountain to the Ogmore Valley. Tight, technical, and exhilarating.',
    waypoints: [
      { lat: 51.6580, lng: -3.5070, name: 'Treorchy' },
      { lat: 51.6720, lng: -3.5380, name: 'Bwlch y Clawdd' },
      { lat: 51.6820, lng: -3.5650, name: 'Summit' },
      { lat: 51.6560, lng: -3.5930, name: 'Nant-y-Moel' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 9,
    difficulty: 'moderate',
    region: 'wales',
    distance_miles: 7,
    tags: ['switchback', 'hairpin', 'twist', 'mountain', 'valley'],
  },
  {
    id: 'a272-sussex',
    name: 'A272 across Sussex',
    description: 'England\'s great cross-country road weaving through the Weald. Gentle curves, rolling hills, and quintessential English countryside.',
    waypoints: [
      { lat: 51.0670, lng: -0.8870, name: 'Petersfield' },
      { lat: 51.0320, lng: -0.7470, name: 'Midhurst' },
      { lat: 50.9900, lng: -0.5400, name: 'Petworth' },
      { lat: 51.0080, lng: -0.3300, name: 'Billingshurst' },
      { lat: 51.0530, lng: -0.1770, name: 'Haywards Heath' },
    ],
    settings: { road_preference: 'curvy' },
    is_public: true,
    curviness_score: 4,
    difficulty: 'easy',
    region: 'england-south',
    distance_miles: 42,
    tags: ['scenic', 'forest', 'dale', 'valley'],
  },
  {
    id: 'b3212-dartmoor',
    name: 'B3212 across Dartmoor',
    description: 'Wild moorland road from Exeter to Yelverton crossing the heart of Dartmoor. Open, exposed, and beautifully bleak.',
    waypoints: [
      { lat: 50.6990, lng: -3.5350, name: 'Dunsford' },
      { lat: 50.6570, lng: -3.6480, name: 'Moretonhampstead' },
      { lat: 50.5810, lng: -3.8200, name: 'Postbridge' },
      { lat: 50.5260, lng: -3.9100, name: 'Two Bridges' },
      { lat: 50.4940, lng: -4.0200, name: 'Yelverton' },
    ],
    settings: { road_preference: 'curvy' },
    is_public: true,
    curviness_score: 5,
    difficulty: 'easy',
    region: 'england-south',
    distance_miles: 28,
    tags: ['moor', 'scenic', 'national park', 'view'],
  },
  {
    id: 'a39-atlantic-highway',
    name: 'A39 Atlantic Highway',
    description: 'Sweeping coastal road from Barnstaple to Bude along North Devon and Cornwall cliffs with sea views and fast flowing bends.',
    waypoints: [
      { lat: 51.0800, lng: -4.0590, name: 'Barnstaple' },
      { lat: 50.9960, lng: -4.2030, name: 'Bideford' },
      { lat: 50.9390, lng: -4.3560, name: 'Clovelly Cross' },
      { lat: 50.8760, lng: -4.4700, name: 'Hartland' },
      { lat: 50.8310, lng: -4.5430, name: 'Bude' },
    ],
    settings: { road_preference: 'fast' },
    is_public: true,
    curviness_score: 4,
    difficulty: 'easy',
    region: 'england-south',
    distance_miles: 38,
    tags: ['coast', 'sea', 'cliff', 'scenic', 'view'],
  },
  {
    id: 'b3306-st-ives-lands-end',
    name: 'B3306 St Ives to Land\'s End',
    description: 'Cornwall\'s finest coastal road hugging dramatic cliffs with tight bends, granite villages, and Atlantic panoramas.',
    waypoints: [
      { lat: 50.2140, lng: -5.4810, name: 'St Ives' },
      { lat: 50.1880, lng: -5.5350, name: 'Zennor' },
      { lat: 50.1540, lng: -5.5930, name: 'Morvah' },
      { lat: 50.1280, lng: -5.6350, name: 'St Just' },
      { lat: 50.0660, lng: -5.7130, name: 'Land\'s End' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 7,
    difficulty: 'moderate',
    region: 'england-south',
    distance_miles: 16,
    tags: ['coast', 'cliff', 'sea', 'scenic', 'bend', 'twist'],
  },
  {
    id: 'nc500-north-coast',
    name: 'NC500 North Coast Section',
    description: 'The wildest stretch of the North Coast 500 along Scotland\'s northern shore from Durness to Thurso through empty single-track roads.',
    waypoints: [
      { lat: 58.4020, lng: -4.7600, name: 'Durness' },
      { lat: 58.4850, lng: -4.4300, name: 'Tongue' },
      { lat: 58.5650, lng: -3.9700, name: 'Bettyhill' },
      { lat: 58.5400, lng: -3.5200, name: 'Melvich' },
      { lat: 58.5930, lng: -3.5230, name: 'Thurso' },
    ],
    settings: { road_preference: 'curvy' },
    is_public: true,
    curviness_score: 5,
    difficulty: 'moderate',
    region: 'scotland',
    distance_miles: 68,
    tags: ['coast', 'highland', 'scenic', 'shore', 'sea'],
  },
  {
    id: 'nc500-west-coast',
    name: 'NC500 West Coast Section',
    description: 'Twisting single-track roads along Scotland\'s dramatic west coast from Ullapool to Durness past pristine beaches and mountain lochs.',
    waypoints: [
      { lat: 57.8940, lng: -5.1600, name: 'Ullapool' },
      { lat: 58.0150, lng: -5.1800, name: 'Ardmair' },
      { lat: 58.1500, lng: -5.0600, name: 'Kylesku' },
      { lat: 58.2500, lng: -5.0500, name: 'Scourie' },
      { lat: 58.3200, lng: -4.9600, name: 'Rhiconich' },
      { lat: 58.4020, lng: -4.7600, name: 'Durness' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 7,
    difficulty: 'moderate',
    region: 'scotland',
    distance_miles: 62,
    tags: ['coast', 'loch', 'highland', 'scenic', 'beach', 'sea'],
  },
  {
    id: 'nc500-east-coast',
    name: 'NC500 East Coast Section',
    description: 'Fast flowing A-road along the east coast from Inverness to John o\' Groats through fishing villages and fertile farmland.',
    waypoints: [
      { lat: 57.4778, lng: -4.2247, name: 'Inverness' },
      { lat: 57.6880, lng: -3.9630, name: 'Tain' },
      { lat: 57.8820, lng: -3.4250, name: 'Helmsdale' },
      { lat: 58.1500, lng: -3.2900, name: 'Wick' },
      { lat: 58.6440, lng: -3.0700, name: 'John o\' Groats' },
    ],
    settings: { road_preference: 'fast' },
    is_public: true,
    curviness_score: 3,
    difficulty: 'easy',
    region: 'scotland',
    distance_miles: 110,
    tags: ['coast', 'highland', 'sea', 'shore', 'scenic'],
  },
  {
    id: 'a836-northern-scotland',
    name: 'A836 Northern Highlands',
    description: 'Remote Highland road from Lairg to Tongue across vast empty moorland with mountain backdrops. True wilderness riding.',
    waypoints: [
      { lat: 58.0200, lng: -4.4020, name: 'Lairg' },
      { lat: 58.1650, lng: -4.4800, name: 'Crask Inn' },
      { lat: 58.2800, lng: -4.5100, name: 'Altnaharra' },
      { lat: 58.4850, lng: -4.4300, name: 'Tongue' },
    ],
    settings: { road_preference: 'curvy' },
    is_public: true,
    curviness_score: 4,
    difficulty: 'moderate',
    region: 'scotland',
    distance_miles: 38,
    tags: ['moor', 'highland', 'scenic', 'mountain'],
  },
  {
    id: 'a838-cape-wrath',
    name: 'A838 Cape Wrath Road',
    description: 'Britain\'s most remote road along the northwest corner of Scotland. Single-track with breathtaking sea cliffs and pristine beaches.',
    waypoints: [
      { lat: 58.4020, lng: -4.7600, name: 'Durness' },
      { lat: 58.3200, lng: -4.9600, name: 'Rhiconich' },
      { lat: 58.2530, lng: -5.0500, name: 'Laxford Bridge' },
      { lat: 58.1500, lng: -5.0600, name: 'Kylesku' },
    ],
    settings: { road_preference: 'curvy' },
    is_public: true,
    curviness_score: 6,
    difficulty: 'moderate',
    region: 'scotland',
    distance_miles: 24,
    tags: ['coast', 'cliff', 'sea', 'highland', 'scenic', 'shore'],
  },
  {
    id: 'buttertubs-pass',
    name: 'Buttertubs Pass',
    description: 'Iconic Yorkshire Dales pass connecting Hawes to Thwaite with steep gradients, cattle grids, and phenomenal dale views.',
    waypoints: [
      { lat: 54.3260, lng: -2.1970, name: 'Hawes' },
      { lat: 54.3470, lng: -2.2260, name: 'Buttertubs Summit' },
      { lat: 54.3720, lng: -2.2080, name: 'Thwaite' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 7,
    difficulty: 'moderate',
    region: 'england-north',
    distance_miles: 6,
    tags: ['pass', 'dale', 'scenic', 'bend', 'moor', 'view'],
  },
  {
    id: 'fleet-moss',
    name: 'Fleet Moss',
    description: 'Yorkshire\'s highest road climbing to 589m with brutal gradients and exposed moorland. A true test piece for any rider.',
    waypoints: [
      { lat: 54.2270, lng: -2.0200, name: 'Buckden' },
      { lat: 54.2170, lng: -2.0990, name: 'Fleet Moss Summit' },
      { lat: 54.2380, lng: -2.1520, name: 'Gayle' },
      { lat: 54.3260, lng: -2.1970, name: 'Hawes' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 6,
    difficulty: 'moderate',
    region: 'england-north',
    distance_miles: 8,
    tags: ['moor', 'pass', 'hill', 'dale', 'summit'],
  },
  {
    id: 'kirkstone-pass',
    name: 'Kirkstone Pass',
    description: 'The Lake District\'s highest pass connecting Ambleside to Ullswater with dramatic fell scenery and sweeping descents.',
    waypoints: [
      { lat: 54.4300, lng: -2.9600, name: 'Ambleside' },
      { lat: 54.4480, lng: -2.9350, name: 'The Struggle' },
      { lat: 54.4650, lng: -2.9180, name: 'Kirkstone Summit' },
      { lat: 54.4900, lng: -2.9050, name: 'Brothers Water' },
      { lat: 54.5270, lng: -2.8750, name: 'Patterdale' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 7,
    difficulty: 'moderate',
    region: 'england-north',
    distance_miles: 10,
    tags: ['pass', 'fell', 'scenic', 'lake', 'bend', 'summit'],
  },
  {
    id: 'a686-penrith-haydon-bridge',
    name: 'A686 Penrith to Haydon Bridge',
    description: 'Epic cross-Pennine road climbing to Hartside Summit (580m) with a famous cafe at the top and long sweeping descents.',
    waypoints: [
      { lat: 54.6640, lng: -2.7550, name: 'Penrith' },
      { lat: 54.7100, lng: -2.5900, name: 'Langwathby' },
      { lat: 54.7380, lng: -2.4750, name: 'Hartside Summit' },
      { lat: 54.7750, lng: -2.3400, name: 'Alston' },
      { lat: 54.8350, lng: -2.2100, name: 'Whitfield' },
      { lat: 54.9720, lng: -2.1500, name: 'Haydon Bridge' },
    ],
    settings: { road_preference: 'fast' },
    is_public: true,
    curviness_score: 5,
    difficulty: 'moderate',
    region: 'england-north',
    distance_miles: 32,
    tags: ['summit', 'moor', 'scenic', 'hill', 'pennine', 'view'],
  },
  {
    id: 'a689-weardale',
    name: 'A689 through Weardale',
    description: 'Beautiful Pennine valley road following the River Wear through historic lead-mining country with gentle flowing curves.',
    waypoints: [
      { lat: 54.7850, lng: -1.8700, name: 'Crook' },
      { lat: 54.7600, lng: -1.9820, name: 'Wolsingham' },
      { lat: 54.7450, lng: -2.1100, name: 'Stanhope' },
      { lat: 54.7350, lng: -2.2500, name: 'St John\'s Chapel' },
      { lat: 54.7200, lng: -2.3700, name: 'Cowshill' },
    ],
    settings: { road_preference: 'curvy' },
    is_public: true,
    curviness_score: 4,
    difficulty: 'easy',
    region: 'england-north',
    distance_miles: 28,
    tags: ['dale', 'valley', 'scenic', 'pennine'],
  },
  {
    id: 'military-road-b6318',
    name: 'Military Road (B6318) Hadrian\'s Wall',
    description: 'Arrow-straight Roman road following Hadrian\'s Wall with undulating rises and falls across windswept Northumbrian moorland.',
    waypoints: [
      { lat: 54.9910, lng: -2.6030, name: 'Greenhead' },
      { lat: 54.9900, lng: -2.3800, name: 'Steel Rigg' },
      { lat: 55.0000, lng: -2.2100, name: 'Housesteads Fort' },
      { lat: 55.0050, lng: -1.9800, name: 'Chollerford' },
      { lat: 55.0200, lng: -1.7400, name: 'Corbridge' },
    ],
    settings: { road_preference: 'fast' },
    is_public: true,
    curviness_score: 3,
    difficulty: 'easy',
    region: 'england-north',
    distance_miles: 30,
    tags: ['moor', 'scenic', 'view', 'hill'],
  },
  {
    id: 'the-struggle-kirkstone',
    name: 'The Struggle (Ambleside to Kirkstone)',
    description: 'The old road up Kirkstone with fearsome 1-in-4 gradients and tight bends climbing from Ambleside. Not for the faint-hearted.',
    waypoints: [
      { lat: 54.4300, lng: -2.9600, name: 'Ambleside' },
      { lat: 54.4380, lng: -2.9450, name: 'Lower Bends' },
      { lat: 54.4480, lng: -2.9350, name: 'Mid Section' },
      { lat: 54.4600, lng: -2.9220, name: 'Upper Bends' },
      { lat: 54.4650, lng: -2.9180, name: 'Kirkstone Pass Inn' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 9,
    difficulty: 'challenging',
    region: 'england-north',
    distance_miles: 3,
    tags: ['hairpin', 'fell', 'bend', 'pass', 'switchback'],
  },
  {
    id: 'cheddar-gorge-b3135',
    name: 'Cheddar Gorge (B3135)',
    description: 'Dramatic limestone gorge with towering cliffs and sweeping curves through England\'s deepest natural gorge.',
    waypoints: [
      { lat: 51.2870, lng: -2.7630, name: 'Cheddar Village' },
      { lat: 51.2920, lng: -2.7730, name: 'Gorge Entrance' },
      { lat: 51.3010, lng: -2.7900, name: 'Upper Gorge' },
      { lat: 51.3120, lng: -2.8030, name: 'Gorge Top' },
    ],
    settings: { road_preference: 'curvy' },
    is_public: true,
    curviness_score: 6,
    difficulty: 'easy',
    region: 'england-south',
    distance_miles: 4,
    tags: ['cliff', 'scenic', 'bend', 'curv', 'valley'],
  },
  {
    id: 'porlock-hill-a39',
    name: 'Porlock Hill (A39)',
    description: 'Infamous Somerset hill with 1-in-4 gradients and sharp hairpins climbing from Porlock to Exmoor. Notorious and thrilling.',
    waypoints: [
      { lat: 51.2120, lng: -3.5930, name: 'Porlock' },
      { lat: 51.2050, lng: -3.5750, name: 'Lower Hairpins' },
      { lat: 51.1980, lng: -3.5600, name: 'Porlock Hill Top' },
      { lat: 51.1850, lng: -3.5380, name: 'Countisbury' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 8,
    difficulty: 'challenging',
    region: 'england-south',
    distance_miles: 5,
    tags: ['hairpin', 'hill', 'coast', 'scenic', 'bend'],
  },
  {
    id: 'combe-martin-lynmouth',
    name: 'Combe Martin to Lynmouth (A399/A39)',
    description: 'Spectacular North Devon coast road plunging through wooded valleys to the sea with vertiginous drops and tight bends.',
    waypoints: [
      { lat: 51.2010, lng: -3.9840, name: 'Combe Martin' },
      { lat: 51.2260, lng: -3.8880, name: 'Blackmoor Gate' },
      { lat: 51.2270, lng: -3.8160, name: 'Parracombe' },
      { lat: 51.2290, lng: -3.7120, name: 'Lynton' },
      { lat: 51.2310, lng: -3.7020, name: 'Lynmouth' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 7,
    difficulty: 'moderate',
    region: 'england-south',
    distance_miles: 15,
    tags: ['coast', 'cliff', 'valley', 'forest', 'scenic', 'bend'],
  },
  {
    id: 'llanberis-pass-a4086',
    name: 'Llanberis Pass (A4086)',
    description: 'Dramatic pass through the heart of Snowdonia beneath the north face of Snowdon. Tight, technical, and utterly stunning.',
    waypoints: [
      { lat: 53.1200, lng: -4.1290, name: 'Llanberis' },
      { lat: 53.0940, lng: -4.0680, name: 'Nant Peris' },
      { lat: 53.0750, lng: -4.0250, name: 'Pen-y-Pass' },
      { lat: 53.0600, lng: -3.9850, name: 'Nant Gwynant' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 7,
    difficulty: 'moderate',
    region: 'wales',
    distance_miles: 8,
    tags: ['pass', 'mountain', 'snowdon', 'scenic', 'twist', 'national park'],
  },
  {
    id: 'crimea-pass-a470',
    name: 'Crimea Pass (A470)',
    description: 'Fast sweeping road between Blaenau Ffestiniog and Dolwyddelan through dark slate quarry landscape. Atmospheric and rapid.',
    waypoints: [
      { lat: 52.9950, lng: -3.9380, name: 'Blaenau Ffestiniog' },
      { lat: 52.9730, lng: -3.9050, name: 'Crimea Summit' },
      { lat: 52.9500, lng: -3.8700, name: 'Dolwyddelan' },
      { lat: 52.9200, lng: -3.8200, name: 'Betws-y-Coed' },
    ],
    settings: { road_preference: 'fast' },
    is_public: true,
    curviness_score: 5,
    difficulty: 'easy',
    region: 'wales',
    distance_miles: 12,
    tags: ['pass', 'scenic', 'valley', 'forest'],
  },
  {
    id: 'gospel-pass',
    name: 'Gospel Pass',
    description: 'Narrow single-track road over the Black Mountains. Wales\' highest road at 549m with remote moorland and sweeping views.',
    waypoints: [
      { lat: 51.9520, lng: -3.0930, name: 'Hay-on-Wye' },
      { lat: 51.9180, lng: -3.1200, name: 'Capel-y-ffin' },
      { lat: 51.8950, lng: -3.1100, name: 'Gospel Pass Summit' },
      { lat: 51.8480, lng: -3.0700, name: 'Llanvihangel Crucorney' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 6,
    difficulty: 'moderate',
    region: 'wales',
    distance_miles: 12,
    tags: ['pass', 'mountain', 'moor', 'scenic', 'summit', 'view'],
  },
  {
    id: 'brecon-beacons-loop',
    name: 'Brecon Beacons Grand Loop',
    description: 'Circuit of the Brecon Beacons combining the A4069, A4067 and mountain roads through some of Wales\' finest riding country.',
    waypoints: [
      { lat: 51.9450, lng: -3.3980, name: 'Brecon' },
      { lat: 51.8700, lng: -3.5200, name: 'Sennybridge' },
      { lat: 51.8600, lng: -3.8200, name: 'Black Mountain Summit' },
      { lat: 51.7950, lng: -3.8700, name: 'Brynamman' },
      { lat: 51.7900, lng: -3.6900, name: 'Ystradgynlais' },
      { lat: 51.8420, lng: -3.5300, name: 'Dan-yr-Ogof' },
      { lat: 51.9450, lng: -3.3980, name: 'Brecon' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 7,
    difficulty: 'moderate',
    region: 'wales',
    distance_miles: 55,
    tags: ['mountain', 'brecon', 'moor', 'national park', 'scenic', 'pass'],
  },
  {
    id: 'isle-of-man-tt-course',
    name: 'Isle of Man TT Course (Snaefell Mountain Course)',
    description: 'The world\'s most famous motorcycle road race circuit. 37.73 miles of public road through villages, over mountain, and along coast.',
    waypoints: [
      { lat: 54.1518, lng: -4.4780, name: 'Douglas (Grandstand)' },
      { lat: 54.1930, lng: -4.4470, name: 'Union Mills' },
      { lat: 54.2230, lng: -4.4280, name: 'Crosby' },
      { lat: 54.2710, lng: -4.4620, name: 'Kirk Michael' },
      { lat: 54.3200, lng: -4.4390, name: 'Ramsey' },
      { lat: 54.2690, lng: -4.3970, name: 'Snaefell Mountain' },
      { lat: 54.1750, lng: -4.4250, name: 'Creg-ny-Baa' },
      { lat: 54.1518, lng: -4.4780, name: 'Douglas (Grandstand)' },
    ],
    settings: { road_preference: 'fast' },
    is_public: true,
    curviness_score: 8,
    difficulty: 'challenging',
    region: 'isle-of-man',
    distance_miles: 38,
    tags: ['bend', 'mountain', 'coast', 'twist', 'scenic'],
  },
  {
    id: 'a85-glen-ogle',
    name: 'A85 through Glen Ogle',
    description: 'Scotland\'s Khyber Pass — a dramatic climb through a narrow Highland glen with steep-sided rocky walls and fast bends.',
    waypoints: [
      { lat: 56.3830, lng: -4.3140, name: 'Lochearnhead' },
      { lat: 56.4220, lng: -4.3400, name: 'Glen Ogle Viaduct' },
      { lat: 56.4560, lng: -4.3050, name: 'Lix Toll' },
      { lat: 56.4700, lng: -4.3200, name: 'Killin' },
    ],
    settings: { road_preference: 'curvy' },
    is_public: true,
    curviness_score: 5,
    difficulty: 'easy',
    region: 'scotland',
    distance_miles: 10,
    tags: ['glen', 'highland', 'scenic', 'valley'],
  },
  {
    id: 'a9-drumochter-pass',
    name: 'A9 Drumochter Pass',
    description: 'Britain\'s highest A-road crossing at 462m through the Cairngorms. Fast dual carriageway with dramatic Highland scenery.',
    waypoints: [
      { lat: 56.7290, lng: -3.9960, name: 'Pitlochry' },
      { lat: 56.7850, lng: -4.0300, name: 'Blair Atholl' },
      { lat: 56.8700, lng: -4.2400, name: 'Drumochter Summit' },
      { lat: 57.0000, lng: -4.2200, name: 'Newtonmore' },
      { lat: 57.0480, lng: -4.1500, name: 'Kingussie' },
    ],
    settings: { road_preference: 'fast' },
    is_public: true,
    curviness_score: 3,
    difficulty: 'easy',
    region: 'scotland',
    distance_miles: 35,
    tags: ['highland', 'mountain', 'scenic', 'summit', 'cairngorm'],
  },
  {
    id: 'cairngorm-loop',
    name: 'Cairngorm Loop (Tomintoul & Lecht)',
    description: 'Remote Cairngorm circuit via the Lecht ski road climbing to 665m. Snow gates in winter, brilliant flowing bends in summer.',
    waypoints: [
      { lat: 57.1480, lng: -3.4000, name: 'Grantown-on-Spey' },
      { lat: 57.1990, lng: -3.3750, name: 'Tomintoul' },
      { lat: 57.1600, lng: -3.2800, name: 'Lecht Summit' },
      { lat: 57.1320, lng: -3.1700, name: 'Cock Bridge' },
      { lat: 57.0850, lng: -3.0900, name: 'Corgarff' },
      { lat: 57.1480, lng: -3.4000, name: 'Grantown-on-Spey' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 6,
    difficulty: 'moderate',
    region: 'scotland',
    distance_miles: 42,
    tags: ['mountain', 'cairngorm', 'highland', 'pass', 'summit', 'scenic'],
  },
  {
    id: 'a93-devils-elbow',
    name: 'A93 Devil\'s Elbow Approach',
    description: 'Old military road climbing to the Cairnwell Pass (670m) — Britain\'s highest main road. The original Devil\'s Elbow hairpins remain nearby.',
    waypoints: [
      { lat: 56.8720, lng: -3.4100, name: 'Blairgowrie' },
      { lat: 56.8900, lng: -3.5200, name: 'Bridge of Cally' },
      { lat: 56.9100, lng: -3.6400, name: 'Spittal of Glenshee' },
      { lat: 56.8790, lng: -3.3770, name: 'Cairnwell Summit' },
      { lat: 57.0200, lng: -3.4300, name: 'Braemar' },
    ],
    settings: { road_preference: 'curvy' },
    is_public: true,
    curviness_score: 6,
    difficulty: 'moderate',
    region: 'scotland',
    distance_miles: 30,
    tags: ['pass', 'mountain', 'highland', 'summit', 'cairngorm'],
  },
  {
    id: 'dukes-pass-a821',
    name: 'Duke\'s Pass (A821, Trossachs)',
    description: 'Classic Trossachs road winding through ancient oak forest between Aberfoyle and Loch Katrine with tight wooded bends.',
    waypoints: [
      { lat: 56.1780, lng: -4.3840, name: 'Aberfoyle' },
      { lat: 56.2050, lng: -4.3600, name: 'Duke\'s Pass Summit' },
      { lat: 56.2360, lng: -4.3900, name: 'Loch Achray' },
      { lat: 56.2500, lng: -4.4200, name: 'Trossachs Pier' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 7,
    difficulty: 'moderate',
    region: 'scotland',
    distance_miles: 8,
    tags: ['forest', 'loch', 'scenic', 'twist', 'bend'],
  },
  {
    id: 'rest-and-be-thankful-a83',
    name: 'Rest and Be Thankful (A83)',
    description: 'Famous Highland pass through Glen Croe with sweeping curves climbing to the summit viewpoint. Dramatic in all conditions.',
    waypoints: [
      { lat: 56.1780, lng: -4.8560, name: 'Arrochar' },
      { lat: 56.2000, lng: -4.8350, name: 'Glen Croe' },
      { lat: 56.2270, lng: -4.8100, name: 'Rest and Be Thankful Summit' },
      { lat: 56.2560, lng: -4.7600, name: 'Cairndow' },
    ],
    settings: { road_preference: 'curvy' },
    is_public: true,
    curviness_score: 6,
    difficulty: 'moderate',
    region: 'scotland',
    distance_miles: 9,
    tags: ['glen', 'pass', 'highland', 'scenic', 'mountain', 'view'],
  },
  {
    id: 'mam-tor-winnats-pass',
    name: 'Mam Tor & Winnats Pass',
    description: 'Dramatic limestone gorge road with tight switchbacks beneath towering crags. The Peak District\'s most spectacular short ride.',
    waypoints: [
      { lat: 53.3490, lng: -1.8100, name: 'Castleton' },
      { lat: 53.3420, lng: -1.8250, name: 'Winnats Pass' },
      { lat: 53.3360, lng: -1.8450, name: 'Speedwell Cavern' },
      { lat: 53.3480, lng: -1.8090, name: 'Mam Tor viewpoint' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 8,
    difficulty: 'moderate',
    region: 'england-midlands',
    distance_miles: 4,
    tags: ['pass', 'cliff', 'twist', 'scenic', 'bend', 'valley'],
  },
  {
    id: 'loch-lomond-to-oban',
    name: 'Loch Lomond to Oban Coastal',
    description: 'Stunning west coast route from Loch Lomond through Crianlarich and along Loch Awe to the fishing port of Oban.',
    waypoints: [
      { lat: 56.0770, lng: -4.5830, name: 'Tarbet (Loch Lomond)' },
      { lat: 56.1780, lng: -4.8560, name: 'Arrochar' },
      { lat: 56.3900, lng: -4.5870, name: 'Crianlarich' },
      { lat: 56.4330, lng: -4.7130, name: 'Tyndrum' },
      { lat: 56.4170, lng: -5.0700, name: 'Dalmally' },
      { lat: 56.4150, lng: -5.4720, name: 'Oban' },
    ],
    settings: { road_preference: 'curvy' },
    is_public: true,
    curviness_score: 5,
    difficulty: 'easy',
    region: 'scotland',
    distance_miles: 60,
    tags: ['loch', 'coast', 'scenic', 'highland', 'sea'],
  },
  {
    id: 'jurassic-coast-dorset',
    name: 'Jurassic Coast Road (Dorset)',
    description: 'Undulating coastal road through Dorset\'s World Heritage coastline past Lulworth Cove, Durdle Door, and golden beaches.',
    waypoints: [
      { lat: 50.6120, lng: -2.4580, name: 'Weymouth' },
      { lat: 50.6220, lng: -2.3170, name: 'Osmington' },
      { lat: 50.6340, lng: -2.2490, name: 'Lulworth Cove' },
      { lat: 50.6450, lng: -2.1170, name: 'Corfe Castle' },
      { lat: 50.6420, lng: -1.9610, name: 'Swanage' },
    ],
    settings: { road_preference: 'curvy' },
    is_public: true,
    curviness_score: 5,
    difficulty: 'easy',
    region: 'england-south',
    distance_miles: 32,
    tags: ['coast', 'cliff', 'sea', 'scenic', 'beach', 'bay'],
  },
  {
    id: 'north-york-moors-circuit',
    name: 'North York Moors Circuit',
    description: 'Sweeping moorland roads through the North York Moors with stunning valley plunges to Rosedale and Farndale.',
    waypoints: [
      { lat: 54.2380, lng: -0.7950, name: 'Helmsley' },
      { lat: 54.3100, lng: -0.8600, name: 'Blakey Ridge' },
      { lat: 54.3530, lng: -0.9250, name: 'Rosedale Head' },
      { lat: 54.3850, lng: -1.0200, name: 'Hutton-le-Hole' },
      { lat: 54.3000, lng: -1.0800, name: 'Kirkbymoorside' },
      { lat: 54.2380, lng: -0.7950, name: 'Helmsley' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 7,
    difficulty: 'moderate',
    region: 'england-north',
    distance_miles: 40,
    tags: ['moor', 'dale', 'scenic', 'bend', 'valley', 'view'],
  },
  {
    id: 'scottish-borders-loop',
    name: 'Scottish Borders Loop',
    description: 'Rolling Border country circuit through the Cheviots and Tweed valley. Empty roads, fast sweepers, and rich history.',
    waypoints: [
      { lat: 55.5990, lng: -2.7270, name: 'Jedburgh' },
      { lat: 55.5420, lng: -2.4800, name: 'Kelso' },
      { lat: 55.5980, lng: -2.5130, name: 'Coldstream' },
      { lat: 55.7690, lng: -2.7000, name: 'Lauder' },
      { lat: 55.5960, lng: -2.8050, name: 'Melrose' },
      { lat: 55.5990, lng: -2.7270, name: 'Jedburgh' },
    ],
    settings: { road_preference: 'fast' },
    is_public: true,
    curviness_score: 4,
    difficulty: 'easy',
    region: 'scotland',
    distance_miles: 55,
    tags: ['scenic', 'valley', 'hill', 'moor'],
  },
  {
    id: 'welsh-valleys-run',
    name: 'Welsh Valleys Run',
    description: 'Exhilarating series of valley-to-valley climbs through the South Wales valleys. Tight bends, steep gradients, and endless switchbacks.',
    waypoints: [
      { lat: 51.7490, lng: -3.3800, name: 'Merthyr Tydfil' },
      { lat: 51.6900, lng: -3.4500, name: 'Aberdare' },
      { lat: 51.6580, lng: -3.5070, name: 'Treorchy' },
      { lat: 51.6280, lng: -3.5800, name: 'Nant-y-Moel' },
      { lat: 51.6100, lng: -3.6500, name: 'Maesteg' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 8,
    difficulty: 'moderate',
    region: 'wales',
    distance_miles: 25,
    tags: ['twist', 'switchback', 'valley', 'mountain', 'bend'],
  },
  {
    id: 'snowdonia-grand-loop',
    name: 'Snowdonia Grand Loop',
    description: 'Epic circuit of Snowdonia National Park combining passes, lakes, and coastal roads. The ultimate Welsh day ride.',
    waypoints: [
      { lat: 53.0200, lng: -3.8300, name: 'Betws-y-Coed' },
      { lat: 53.0560, lng: -3.9500, name: 'Capel Curig' },
      { lat: 53.0750, lng: -4.0250, name: 'Pen-y-Pass' },
      { lat: 53.1200, lng: -4.1290, name: 'Llanberis' },
      { lat: 53.1380, lng: -4.2750, name: 'Caernarfon' },
      { lat: 52.9280, lng: -4.1270, name: 'Beddgelert' },
      { lat: 53.0200, lng: -3.8300, name: 'Betws-y-Coed' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 7,
    difficulty: 'moderate',
    region: 'wales',
    distance_miles: 55,
    tags: ['snowdon', 'pass', 'mountain', 'national park', 'lake', 'scenic'],
  },
  {
    id: 'peak-district-loop',
    name: 'Peak District Loop',
    description: 'Classic Peak District circuit linking Snake Pass, Woodhead, and the Cat and Fiddle with moorland and reservoir views.',
    waypoints: [
      { lat: 53.2350, lng: -1.7900, name: 'Bakewell' },
      { lat: 53.2830, lng: -1.6170, name: 'Chatsworth' },
      { lat: 53.3490, lng: -1.8100, name: 'Castleton' },
      { lat: 53.4180, lng: -1.8640, name: 'Snake Summit' },
      { lat: 53.4430, lng: -1.9490, name: 'Glossop' },
      { lat: 53.3560, lng: -2.0050, name: 'Whaley Bridge' },
      { lat: 53.2601, lng: -2.1253, name: 'Macclesfield' },
      { lat: 53.2361, lng: -1.9873, name: 'Cat and Fiddle' },
      { lat: 53.2594, lng: -1.9145, name: 'Buxton' },
      { lat: 53.2350, lng: -1.7900, name: 'Bakewell' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 7,
    difficulty: 'moderate',
    region: 'england-midlands',
    distance_miles: 65,
    tags: ['moor', 'pass', 'snake', 'twist', 'scenic', 'bend'],
  },
  {
    id: 'lake-district-grand-tour',
    name: 'Lake District Grand Tour',
    description: 'Epic full-day circuit of the Lake District taking in Kirkstone, Honister, Hardknott, and Wrynose passes with lake and fell views.',
    waypoints: [
      { lat: 54.5920, lng: -2.9580, name: 'Keswick' },
      { lat: 54.5100, lng: -3.1950, name: 'Honister Pass' },
      { lat: 54.4520, lng: -3.2800, name: 'Wasdale Head' },
      { lat: 54.4020, lng: -3.2130, name: 'Hardknott Pass' },
      { lat: 54.4210, lng: -3.1270, name: 'Wrynose Pass' },
      { lat: 54.4300, lng: -2.9600, name: 'Ambleside' },
      { lat: 54.4650, lng: -2.9180, name: 'Kirkstone Pass' },
      { lat: 54.5270, lng: -2.8750, name: 'Patterdale' },
      { lat: 54.5920, lng: -2.9580, name: 'Keswick' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 9,
    difficulty: 'challenging',
    region: 'england-north',
    distance_miles: 75,
    tags: ['pass', 'fell', 'lake', 'mountain', 'scenic', 'hairpin', 'switchback'],
  },
  {
    id: 'scottish-borders-route',
    name: 'Scottish Borders Abbeys Route',
    description: 'Gentle touring route connecting the four great Border abbeys through rolling farmland and wooded river valleys.',
    waypoints: [
      { lat: 55.5960, lng: -2.8050, name: 'Melrose' },
      { lat: 55.5480, lng: -2.8680, name: 'Selkirk' },
      { lat: 55.4230, lng: -2.7890, name: 'Hawick' },
      { lat: 55.5990, lng: -2.7270, name: 'Jedburgh' },
      { lat: 55.5420, lng: -2.4800, name: 'Kelso' },
      { lat: 55.5960, lng: -2.8050, name: 'Melrose' },
    ],
    settings: { road_preference: 'curvy' },
    is_public: true,
    curviness_score: 4,
    difficulty: 'easy',
    region: 'scotland',
    distance_miles: 60,
    tags: ['scenic', 'valley', 'hill', 'forest'],
  },
  {
    id: 'cotswolds-scenic-run',
    name: 'Cotswolds Scenic Run',
    description: 'Leisurely circuit through honey-stone villages, rolling wolds, and gentle sweeping bends. Quintessential English touring.',
    waypoints: [
      { lat: 51.9340, lng: -1.7050, name: 'Stow-on-the-Wold' },
      { lat: 51.9860, lng: -1.7810, name: 'Moreton-in-Marsh' },
      { lat: 52.0580, lng: -1.7100, name: 'Chipping Campden' },
      { lat: 52.0430, lng: -1.8600, name: 'Broadway' },
      { lat: 51.9920, lng: -1.9430, name: 'Winchcombe' },
      { lat: 51.8870, lng: -1.8830, name: 'Bourton-on-the-Water' },
      { lat: 51.9340, lng: -1.7050, name: 'Stow-on-the-Wold' },
    ],
    settings: { road_preference: 'curvy' },
    is_public: true,
    curviness_score: 3,
    difficulty: 'easy',
    region: 'england-midlands',
    distance_miles: 45,
    tags: ['scenic', 'valley', 'view', 'hill'],
  },
  {
    id: 'south-downs-way-road',
    name: 'South Downs Way Road Route',
    description: 'Following the chalk escarpment of the South Downs from Winchester to Eastbourne with sweeping views north and south.',
    waypoints: [
      { lat: 51.0640, lng: -1.3080, name: 'Winchester' },
      { lat: 50.9830, lng: -1.0200, name: 'West Meon' },
      { lat: 50.9550, lng: -0.7340, name: 'South Harting' },
      { lat: 50.9060, lng: -0.5070, name: 'Amberley' },
      { lat: 50.8810, lng: -0.2730, name: 'Steyning' },
      { lat: 50.8420, lng: 0.0080, name: 'Lewes' },
      { lat: 50.7690, lng: 0.2840, name: 'Eastbourne' },
    ],
    settings: { road_preference: 'curvy' },
    is_public: true,
    curviness_score: 4,
    difficulty: 'easy',
    region: 'england-south',
    distance_miles: 80,
    tags: ['scenic', 'hill', 'dale', 'view'],
  },
  {
    id: 'honister-pass',
    name: 'Honister Pass',
    description: 'Steep and narrow Lake District pass through dramatic slate quarry scenery. 25% gradients and stunning Borrowdale views.',
    waypoints: [
      { lat: 54.5550, lng: -3.1540, name: 'Borrowdale' },
      { lat: 54.5280, lng: -3.1730, name: 'Seatoller' },
      { lat: 54.5100, lng: -3.1950, name: 'Honister Summit' },
      { lat: 54.4870, lng: -3.2650, name: 'Buttermere' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 8,
    difficulty: 'challenging',
    region: 'england-north',
    distance_miles: 7,
    tags: ['pass', 'fell', 'scenic', 'bend', 'mountain'],
  },
  {
    id: 'a4086-snowdon-horseshoe',
    name: 'A4086 Snowdon Horseshoe',
    description: 'Circle of Snowdon via Llanberis Pass, Pen-y-Pass and down through Nant Gwynant to Beddgelert. Wales\' finest mountain circuit.',
    waypoints: [
      { lat: 53.1200, lng: -4.1290, name: 'Llanberis' },
      { lat: 53.0750, lng: -4.0250, name: 'Pen-y-Pass' },
      { lat: 53.0170, lng: -4.0150, name: 'Nant Gwynant' },
      { lat: 52.9900, lng: -4.0980, name: 'Beddgelert' },
      { lat: 53.0500, lng: -4.2000, name: 'Rhyd-Ddu' },
      { lat: 53.1200, lng: -4.1290, name: 'Llanberis' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 7,
    difficulty: 'moderate',
    region: 'wales',
    distance_miles: 28,
    tags: ['snowdon', 'pass', 'mountain', 'lake', 'scenic', 'national park'],
  },
  {
    id: 'evo-triangle',
    name: 'Evo Triangle (North Wales)',
    description: 'The legendary road test triangle used by car magazines: A543, A5, and B4501. Fast sweepers and technical tight sections.',
    waypoints: [
      { lat: 53.0920, lng: -3.4760, name: 'Pentrefoelas' },
      { lat: 53.0600, lng: -3.5600, name: 'Sportsman\'s Arms' },
      { lat: 53.0450, lng: -3.4500, name: 'Cerrigydrudion' },
      { lat: 53.0920, lng: -3.4760, name: 'Pentrefoelas' },
    ],
    settings: { road_preference: 'fast' },
    is_public: true,
    curviness_score: 7,
    difficulty: 'moderate',
    region: 'wales',
    distance_miles: 20,
    tags: ['twist', 'bend', 'moor', 'scenic'],
  },
  {
    id: 'great-orme-marine-drive',
    name: 'Great Orme Marine Drive',
    description: 'Toll road circuit of the Great Orme headland at Llandudno with dramatic sea cliffs and panoramic coastal views.',
    waypoints: [
      { lat: 53.3280, lng: -3.8350, name: 'Llandudno Pier' },
      { lat: 53.3420, lng: -3.8570, name: 'Happy Valley' },
      { lat: 53.3470, lng: -3.8700, name: 'Great Orme Summit' },
      { lat: 53.3350, lng: -3.8650, name: 'West Shore' },
      { lat: 53.3280, lng: -3.8350, name: 'Llandudno Pier' },
    ],
    settings: { road_preference: 'curvy' },
    is_public: true,
    curviness_score: 5,
    difficulty: 'easy',
    region: 'wales',
    distance_miles: 5,
    tags: ['coast', 'cliff', 'sea', 'scenic', 'view', 'promenade'],
  },
  {
    id: 'a44-elan-valley',
    name: 'A44 & Elan Valley',
    description: 'Mid-Wales reservoir circuit through the Elan Valley dams and remote mountain roads. Empty, flowing, and wildly beautiful.',
    waypoints: [
      { lat: 52.3020, lng: -3.5250, name: 'Rhayader' },
      { lat: 52.2780, lng: -3.5750, name: 'Caban Coch Dam' },
      { lat: 52.2600, lng: -3.6200, name: 'Craig Goch Dam' },
      { lat: 52.2950, lng: -3.6800, name: 'Claerwen Reservoir' },
      { lat: 52.3020, lng: -3.5250, name: 'Rhayader' },
    ],
    settings: { road_preference: 'curvy' },
    is_public: true,
    curviness_score: 5,
    difficulty: 'easy',
    region: 'wales',
    distance_miles: 22,
    tags: ['lake', 'scenic', 'valley', 'moor', 'view'],
  },
  {
    id: 'a537-goyt-valley',
    name: 'A537 & Goyt Valley Circuit',
    description: 'Extension of the Cat and Fiddle taking in the beautiful Goyt Valley reservoirs and Long Hill road above Buxton.',
    waypoints: [
      { lat: 53.2594, lng: -1.9145, name: 'Buxton' },
      { lat: 53.2880, lng: -1.9750, name: 'Long Hill' },
      { lat: 53.3070, lng: -2.0100, name: 'Goyt Valley' },
      { lat: 53.3200, lng: -2.0200, name: 'Errwood Reservoir' },
      { lat: 53.3560, lng: -2.0050, name: 'Whaley Bridge' },
      { lat: 53.2361, lng: -1.9873, name: 'Cat and Fiddle' },
      { lat: 53.2594, lng: -1.9145, name: 'Buxton' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 7,
    difficulty: 'moderate',
    region: 'england-midlands',
    distance_miles: 25,
    tags: ['twist', 'moor', 'lake', 'scenic', 'bend'],
  },
  {
    id: 'north-pennines-circuit',
    name: 'North Pennines Circuit',
    description: 'England\'s last wilderness — remote moorland roads through the North Pennines AONB connecting Teesdale, Weardale, and Allendale.',
    waypoints: [
      { lat: 54.6530, lng: -2.0780, name: 'Middleton-in-Teesdale' },
      { lat: 54.7130, lng: -2.1460, name: 'Langdon Beck' },
      { lat: 54.7500, lng: -2.3600, name: 'St John\'s Chapel' },
      { lat: 54.7380, lng: -2.4750, name: 'Alston' },
      { lat: 54.8000, lng: -2.3500, name: 'Nenthead' },
      { lat: 54.6530, lng: -2.0780, name: 'Middleton-in-Teesdale' },
    ],
    settings: { road_preference: 'curvy' },
    is_public: true,
    curviness_score: 5,
    difficulty: 'moderate',
    region: 'england-north',
    distance_miles: 55,
    tags: ['moor', 'dale', 'pennine', 'scenic', 'hill'],
  },
  {
    id: 'yorkshire-dales-circuit',
    name: 'Yorkshire Dales Grand Circuit',
    description: 'Complete circuit of the Yorkshire Dales taking in Buttertubs, Fleet Moss, and the spectacular Ribblehead Viaduct.',
    waypoints: [
      { lat: 54.3260, lng: -2.1970, name: 'Hawes' },
      { lat: 54.3720, lng: -2.2080, name: 'Thwaite (Buttertubs)' },
      { lat: 54.4030, lng: -2.2400, name: 'Keld' },
      { lat: 54.3400, lng: -2.3620, name: 'Kirkby Stephen' },
      { lat: 54.2100, lng: -2.3700, name: 'Ribblehead' },
      { lat: 54.1520, lng: -2.3400, name: 'Ingleton' },
      { lat: 54.2270, lng: -2.0200, name: 'Buckden' },
      { lat: 54.3260, lng: -2.1970, name: 'Hawes' },
    ],
    settings: { road_preference: 'twisty' },
    is_public: true,
    curviness_score: 7,
    difficulty: 'moderate',
    region: 'england-north',
    distance_miles: 70,
    tags: ['dale', 'pass', 'moor', 'scenic', 'valley', 'fell'],
  },
  {
    id: 'a5-north-wales',
    name: 'A5 through North Wales (Telford\'s Road)',
    description: 'Historic coaching road from Betws-y-Coed to Bangor through the Ogwen Valley beneath the Carneddau and Glyderau mountains.',
    waypoints: [
      { lat: 53.0200, lng: -3.8300, name: 'Betws-y-Coed' },
      { lat: 53.0560, lng: -3.9500, name: 'Capel Curig' },
      { lat: 53.1150, lng: -4.0010, name: 'Ogwen Valley' },
      { lat: 53.1550, lng: -4.0400, name: 'Bethesda' },
      { lat: 53.2270, lng: -4.1280, name: 'Bangor' },
    ],
    settings: { road_preference: 'fast' },
    is_public: true,
    curviness_score: 5,
    difficulty: 'easy',
    region: 'wales',
    distance_miles: 22,
    tags: ['mountain', 'valley', 'scenic', 'lake', 'national park'],
  },
];

export function getCuratedByRegion(region: string): CuratedRoute[] {
  return curatedRoutes.filter((r) => r.region === region);
}

export function getCuratedByDifficulty(diff: string): CuratedRoute[] {
  return curatedRoutes.filter((r) => r.difficulty === diff);
}

export function searchCurated(query: string): CuratedRoute[] {
  const q = query.toLowerCase();
  return curatedRoutes.filter(
    (r) =>
      r.name.toLowerCase().includes(q) ||
      r.description.toLowerCase().includes(q) ||
      r.tags.some((t) => t.includes(q)) ||
      r.region.includes(q),
  );
}
